name: Checkout Issue Report
description: This is used for reporting an issue with Checkout
title: One-liner to describe the issue
labels: Checkout Production Support
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue with Checkout.
        
        Consider the following before submitting an issue:
        
        - Go through our [playbook](https://checkout.docs.shopify.io/docs/referencedocs/playbooks/playbook) and resources to confirm whether it is a Checkout issue.
        - Validate the issue to the best of your abilities. Provide steps to reproduce when possible. Our tools, logs and resources can help confirm it is an issue.
        - Identify if the issue occurs in Checkout Classic or in Checkout One by following [this guide](https://checkout.docs.shopify.io/docs/referencedocs/debug#checkout-one-or-classic).
        - If there is an incident , page `checkout-oncall`.
        
        **MSMs / Support Advisors, please go through [#support-global-technical](https://shopify.slack.com/archives/C02M3AD04QZ) / [#support-plus-technical](https://shopify.slack.com/archives/C034B096E) first.**
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Give a detail description of the problem
    validations:
      required: true
  - type: dropdown
    id: c1_or_classic
    attributes:
      label: Checkout Classic or Checkout One?
      description: Is the issue occurring on Checkout Classic or Checkout One?
      options:
        - Checkout One
        - Classic
        - Both
    validations:
      required: true
  - type: textarea
    id: buyer_impact
    attributes:
      label: How does this impact the Buyer?
  - type: textarea
    id: merchant_impact
    attributes:
      label: How does this impact the Merchant?
  - type: textarea
    id: identifying_information
    attributes:
      label: Identifying information
      description: |
       **Log retention notice:** Splunk has a limited log retention period which can affect our ability to debug issues. When referencing Splunk logs, be sure to include a copy of the query you ran, and also [export](https://docs.splunk.com/Documentation/Splunk/9.0.2/Search/ExportdatausingSplunkWeb) and [attach](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) a copy of the relevant data to this issue.
      value: |
        Request id:
        Cart id:
        Session token:
        Logs:
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to reproduce
      description: |
        If you are able to reproduce the issue, let us know how to do that.
        Make sure you have tried using the same Buyer's address.
